import React, { useState, useEffect } from 'react';
import { 
  Sparkles, Ruler, Trash2, Plus, Download, Upload, Eye,
  Home, Compass, Grid, FileCheck, RefreshCw, Layers, Layout,
  Check, Edit3, MapPin, Minimize2, Sliders, Settings
} from 'lucide-react';
import { BrandKit } from './CommandPaletteSimulator';

interface ArchitectureDrawingEngineProps {
  activeBrandKit?: BrandKit;
  logTrace: (message: string) => void;
}

export interface ArchWall {
  id: string;
  name: string;
  startX: number; // percentage coordinate on 100x100 grid
  startY: number;
  endX: number;
  endY: number;
  thickness: number; // in mm, e.g. 200, 150
  type: 'exterior' | 'interior';
}

export interface ArchRoom {
  id: string;
  name: string;
  x: number; // grid percentage center
  y: number;
  width: number; // in meters (e.g. 5.4)
  height: number; // in meters (e.g. 4.2)
  flooring: string; // Terrazzo, White Oak, Limestone
  wallFinish: string; // Chalk Wash, Satin Paint, Veneered Panel
}

export interface ArchDoor {
  id: string;
  name: string;
  x: number; // grid percentage location along a wall
  y: number;
  width: number; // in meters (e.g. 0.9)
  angle: number; // open angle degrees (e.g. 90)
  style: 'swing' | 'sliding' | 'bifold';
  orientation: 'left' | 'right';
}

export interface ArchWindow {
  id: string;
  name: string;
  x: number;
  y: number;
  width: number; // in meters (e.g. 1.2)
  glazing: 'double' | 'triple' | 'tempered';
  style: 'fixed' | 'sliding' | 'casement';
}

export default function ArchitectureDrawingEngine({ activeBrandKit, logTrace }: ArchitectureDrawingEngineProps) {
  // Available Scale Presets
  const SCALE_PRESETS = [
    { label: '1:50 (Standard Interior & Construction Details)', value: 50, factor: 0.02 },
    { label: '1:100 (Standard Residential Floor Plans)', value: 100, factor: 0.01 },
    { label: '1:200 (Large Architectural Site Layout Sheets)', value: 200, factor: 0.005 }
  ];

  // Materials & Finishes Presets for Room Schedules
  const FLOORING_PRESETS = [
    'Polished Terrazzo (White Quartz)',
    'Engineered White Oak Planks',
    'Brushed Belgian Limestone',
    'Raw Industrial Screed Concrete',
    'Handcrafted Terracotta Tiles'
  ];

  const WALL_FINISH_PRESETS = [
    'Traditional Chalk Wash (Lime plaster)',
    'Minimal Matte Charcoal Paint',
    'Veneered American Walnut Panels',
    'Satin Off-White Acrylic Coating',
    'Raw Exposed Formwork Concrete'
  ];

  // Presets of layouts generated by createFloorPlan()
  const PRESET_FLOOR_PLANS: Record<string, {
    name: string;
    walls: ArchWall[];
    rooms: ArchRoom[];
    doors: ArchDoor[];
    windows: ArchWindow[];
    scaleValue: number;
  }> = {
    modern_2bed: {
      name: "Modern 2-Bedroom Apartment",
      scaleValue: 50,
      walls: [
        { id: 'w_1', name: 'Exterior North Wall', startX: 10, startY: 10, endX: 90, endY: 10, thickness: 300, type: 'exterior' },
        { id: 'w_2', name: 'Exterior East Wall', startX: 90, startY: 10, endX: 90, endY: 90, thickness: 300, type: 'exterior' },
        { id: 'w_3', name: 'Exterior South Wall', startX: 90, startY: 90, endX: 10, endY: 90, thickness: 300, type: 'exterior' },
        { id: 'w_4', name: 'Exterior West Wall', startX: 10, startY: 90, endX: 10, endY: 10, thickness: 300, type: 'exterior' },
        { id: 'w_5', name: 'Interior Divider Wall 1', startX: 50, startY: 10, endX: 50, endY: 90, thickness: 150, type: 'interior' },
        { id: 'w_6', name: 'Interior Divider Wall 2', startX: 10, startY: 50, endX: 50, endY: 50, thickness: 150, type: 'interior' }
      ],
      rooms: [
        { id: 'r_1', name: 'Master Suite Bedroom', x: 30, y: 30, width: 6.4, height: 4.8, flooring: 'Engineered White Oak Planks', wallFinish: 'Traditional Chalk Wash (Lime plaster)' },
        { id: 'r_2', name: 'Guest Study Lounge', x: 30, y: 70, width: 6.4, height: 4.8, flooring: 'Polished Terrazzo (White Quartz)', wallFinish: 'Satin Off-White Acrylic Coating' },
        { id: 'r_3', name: 'Grand Living & Kitchen', x: 70, y: 50, width: 6.4, height: 9.6, flooring: 'Brushed Belgian Limestone', wallFinish: 'Veneered American Walnut Panels' }
      ],
      doors: [
        { id: 'd_1', name: 'Main Entry Swing Door', x: 10, y: 30, width: 1.0, angle: 90, style: 'swing', orientation: 'right' },
        { id: 'd_2', name: 'Master Suite Privacy Door', x: 50, y: 30, width: 0.9, angle: 90, style: 'swing', orientation: 'left' },
        { id: 'd_3', name: 'Guest Room Sliding Entrance', x: 50, y: 70, width: 1.2, angle: 0, style: 'sliding', orientation: 'right' }
      ],
      windows: [
        { id: 'wi_1', name: 'North Balcony Glazing', x: 30, y: 10, width: 2.4, glazing: 'triple', style: 'sliding' },
        { id: 'wi_2', name: 'Lounge Panoramic Pane', x: 70, y: 10, width: 3.2, glazing: 'triple', style: 'fixed' },
        { id: 'wi_3', name: 'Study East Vent Window', x: 90, y: 50, width: 1.5, glazing: 'double', style: 'casement' }
      ]
    },
    minimalist_studio: {
      name: "Minimalist Loft Studio",
      scaleValue: 100,
      walls: [
        { id: 'w_1', name: 'Outer Perimeter N', startX: 15, startY: 15, endX: 85, endY: 15, thickness: 250, type: 'exterior' },
        { id: 'w_2', name: 'Outer Perimeter E', startX: 85, startY: 15, endX: 85, endY: 85, thickness: 250, type: 'exterior' },
        { id: 'w_3', name: 'Outer Perimeter S', startX: 85, startY: 85, endX: 15, endY: 85, thickness: 250, type: 'exterior' },
        { id: 'w_4', name: 'Outer Perimeter W', startX: 15, startY: 85, endX: 15, endY: 15, thickness: 250, type: 'exterior' },
        { id: 'w_5', name: 'Sanitary Enclosure Wall', startX: 15, startY: 60, endX: 45, endY: 60, thickness: 120, type: 'interior' },
        { id: 'w_6', name: 'Sanitary Return Wall', startX: 45, startY: 60, endX: 45, endY: 85, thickness: 120, type: 'interior' }
      ],
      rooms: [
        { id: 'r_1', name: 'Open Live-Work Studio Space', x: 50, y: 40, width: 11.2, height: 7.2, flooring: 'Raw Industrial Screed Concrete', wallFinish: 'Raw Exposed Formwork Concrete' },
        { id: 'r_2', name: 'Integrated Wet/Bath Cubicle', x: 30, y: 72, width: 4.8, height: 4.0, flooring: 'Brushed Belgian Limestone', wallFinish: 'Minimal Matte Charcoal Paint' }
      ],
      doors: [
        { id: 'd_1', name: 'Loft Front Pivot Door', x: 50, y: 15, width: 1.2, angle: 90, style: 'swing', orientation: 'right' },
        { id: 'd_2', name: 'Bath Flush Pocket Door', x: 45, y: 72, width: 0.8, angle: 0, style: 'sliding', orientation: 'left' }
      ],
      windows: [
        { id: 'wi_1', name: 'South Garden Glass Glazing', x: 50, y: 85, width: 4.8, glazing: 'triple', style: 'sliding' },
        { id: 'wi_2', name: 'North Sky Climatic Window', x: 30, y: 15, width: 1.8, glazing: 'double', style: 'casement' }
      ]
    },
    compact_cabin: {
      name: "Solitary Compact Micro-Cabin",
      scaleValue: 50,
      walls: [
        { id: 'w_1', name: 'Cabin Perimeter North', startX: 20, startY: 20, endX: 80, endY: 20, thickness: 200, type: 'exterior' },
        { id: 'w_2', name: 'Cabin Perimeter East', startX: 80, startY: 20, endX: 80, endY: 80, thickness: 200, type: 'exterior' },
        { id: 'w_3', name: 'Cabin Perimeter South', startX: 80, startY: 80, endX: 20, endY: 80, thickness: 200, type: 'exterior' },
        { id: 'w_4', name: 'Cabin Perimeter West', startX: 20, startY: 80, endX: 20, endY: 20, thickness: 200, type: 'exterior' }
      ],
      rooms: [
        { id: 'r_1', name: 'Fireside All-in-One Studio', x: 50, y: 50, width: 7.2, height: 7.2, flooring: 'Handcrafted Terracotta Tiles', wallFinish: 'Traditional Chalk Wash (Lime plaster)' }
      ],
      doors: [
        { id: 'd_1', name: 'Veranda Entrance Door', x: 50, y: 80, width: 1.0, angle: 90, style: 'swing', orientation: 'right' }
      ],
      windows: [
        { id: 'wi_1', name: 'Stargazer Roof Apex Skylight', x: 50, y: 20, width: 2.0, glazing: 'tempered', style: 'fixed' },
        { id: 'wi_2', name: 'West Lookout Ribbon Pane', x: 20, y: 50, width: 1.6, glazing: 'triple', style: 'sliding' }
      ]
    },
    empty_site: {
      name: "Custom Empty CAD Plot Grid",
      scaleValue: 100,
      walls: [
        { id: 'w_1', name: 'Outer Lot Boundary N', startX: 5, startY: 5, endX: 95, endY: 5, thickness: 400, type: 'exterior' },
        { id: 'w_2', name: 'Outer Lot Boundary E', startX: 95, startY: 5, endX: 95, endY: 95, thickness: 400, type: 'exterior' },
        { id: 'w_3', name: 'Outer Lot Boundary S', startX: 95, startY: 95, endX: 5, endY: 95, thickness: 400, type: 'exterior' },
        { id: 'w_4', name: 'Outer Lot Boundary W', startX: 5, startY: 95, endX: 5, endY: 5, thickness: 400, type: 'exterior' }
      ],
      rooms: [
        { id: 'r_1', name: 'Unpartitioned Zone', x: 50, y: 50, width: 18.0, height: 18.0, flooring: 'Raw Industrial Screed Concrete', wallFinish: 'Raw Exposed Formwork Concrete' }
      ],
      doors: [],
      windows: []
    }
  };

  // State Engine Setup
  const [activePlanName, setActivePlanName] = useState<string>(PRESET_FLOOR_PLANS.modern_2bed.name);
  const [walls, setWalls] = useState<ArchWall[]>(PRESET_FLOOR_PLANS.modern_2bed.walls);
  const [rooms, setRooms] = useState<ArchRoom[]>(PRESET_FLOOR_PLANS.modern_2bed.rooms);
  const [doors, setDoors] = useState<ArchDoor[]>(PRESET_FLOOR_PLANS.modern_2bed.doors);
  const [windows, setWindows] = useState<ArchWindow[]>(PRESET_FLOOR_PLANS.modern_2bed.windows);
  
  const [currentScale, setCurrentScale] = useState(SCALE_PRESETS[0]); // 1:50
  const [activePresentationTab, setActivePresentationTab] = useState<'floor_plan' | 'elevation' | 'section' | 'room_schedule'>('floor_plan');

  const [selectedElementId, setSelectedElementId] = useState<string | null>('r_1');
  const [selectedElementType, setSelectedElementType] = useState<'wall' | 'room' | 'door' | 'window' | null>('room');

  // Scanner upload sequence states
  const [uploadProgress, setUploadProgress] = useState<number | null>(null);
  const [scannerLogStatus, setScannerLogStatus] = useState<string>('');

  // Slices Settings for Section / Elevation Direction selector
  const [activeElevationDirection, setActiveElevationDirection] = useState<'North' | 'South' | 'East' | 'West'>('North');
  const [sectionPlaneX, setSectionPlaneX] = useState<number>(50); // percentage slice coord

  // Quick form state helpers
  const [wallStartXPct, setWallStartXPct] = useState<number>(10);
  const [wallStartYPct, setWallStartYPct] = useState<number>(50);
  const [wallEndXPct, setWallEndXPct] = useState<number>(90);
  const [wallEndYPct, setWallEndYPct] = useState<number>(50);
  const [wallTypeName, setWallTypeName] = useState<'exterior' | 'interior'>('interior');

  const [doorXPct, setDoorXPct] = useState<number>(50);
  const [doorYPct, setDoorYPct] = useState<number>(10);
  const [doorStyleOption, setDoorStyleOption] = useState<'swing' | 'sliding' | 'bifold'>('swing');

  const [winXPct, setWinXPct] = useState<number>(75);
  const [winYPct, setWinYPct] = useState<number>(10);
  const [winStyleOption, setWinStyleOption] = useState<'fixed' | 'sliding' | 'casement'>('sliding');

  const [roomXPct, setRoomXPct] = useState<number>(50);
  const [roomYPct, setRoomYPct] = useState<number>(50);
  const [roomWidthM, setRoomWidthM] = useState<number>(5.5);
  const [roomHeightM, setRoomHeightM] = useState<number>(4.5);
  const [newRoomName, setNewRoomName] = useState<string>('Primary Living Den');

  // Trigger Action Calls
  const createFloorPlan = (presetKey: string) => {
    const pr = PRESET_FLOOR_PLANS[presetKey];
    if (!pr) return;
    setActivePlanName(pr.name);
    setWalls(pr.walls);
    setRooms(pr.rooms);
    setDoors(pr.doors);
    setWindows(pr.windows);
    
    const sc = SCALE_PRESETS.find(s => s.value === pr.scaleValue) || SCALE_PRESETS[0];
    setCurrentScale(sc);
    setSelectedElementId(pr.rooms[0]?.id || null);
    setSelectedElementType('room');
    logTrace(`[ARCH KERNEL] createFloorPlan() executed. Initialized "${pr.name}" space framework with logged CAD scale ${sc.label}.`);
  };

  // Simulate Floor Plan Scanned Line Recognition
  const uploadFloorPlan = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files || e.target.files.length === 0) return;
    const file = e.target.files[0];
    logTrace(`[ARCH Uploader] uploadFloorPlan() triggered for target: "${file.name}" (${(file.size / 1024).toFixed(1)} KB)`);

    // Run custom animated sequential scan
    setUploadProgress(0);
    setScannerLogStatus("Initializing computer vision parser...");
    
    let progVal = 0;
    const tInterval = setInterval(() => {
      progVal += 12;
      if (progVal >= 100) {
        progVal = 100;
        clearInterval(tInterval);
        setTimeout(() => {
          // Finalize sequential detections
          detectWalls();
          detectRooms();
          detectDoors();
          detectWindows();
          
          setUploadProgress(null);
          setScannerLogStatus("");
          logTrace(`[CAD PARSER] Fully synthesized blueprint elements from scanned template successfully!`);
        }, 300);
      }
      setUploadProgress(progVal);

      if (progVal === 24) {
        setScannerLogStatus("Scanning exterior boundary structures... [detectWalls()]");
      } else if (progVal === 48) {
        setScannerLogStatus("Locating partition layouts and rooms... [detectRooms()]");
      } else if (progVal === 72) {
        setScannerLogStatus("Extracting wall gap vectors and anchors... [detectDoors()] [-detectWindows()]");
      } else if (progVal === 96) {
        setScannerLogStatus("Generating complete BIM room schedules and spec sheets...");
      }
    }, 180);
  };

  const detectWalls = () => {
    // Generate simulated randomized walls to construct a brand new micro setup
    const simulatedWalls: ArchWall[] = [
      { id: 'w_d1', name: 'Scanned Boundary N', startX: 12, startY: 12, endX: 88, endY: 12, thickness: 280, type: 'exterior' },
      { id: 'w_d2', name: 'Scanned Boundary E', startX: 88, startY: 12, endX: 88, endY: 88, thickness: 280, type: 'exterior' },
      { id: 'w_d3', name: 'Scanned Boundary S', startX: 88, startY: 88, endX: 12, endY: 88, thickness: 280, type: 'exterior' },
      { id: 'w_d4', name: 'Scanned Boundary W', startX: 12, startY: 88, endX: 12, endY: 12, thickness: 280, type: 'exterior' },
      { id: 'w_d5', name: 'Scanned Partition Centroid', startX: 47, startY: 12, endX: 47, endY: 88, thickness: 140, type: 'interior' }
    ];
    setWalls(simulatedWalls);
    logTrace(`[CORE CALL] detectWalls() complete: Resolved ${simulatedWalls.length} primary spatial partitions.`);
  };

  const detectRooms = () => {
    const simulatedRooms: ArchRoom[] = [
      { id: 'r_d1', name: 'Scanned Lounge Suite', x: 30, y: 50, width: 5.6, height: 7.6, flooring: 'Engineered White Oak Planks', wallFinish: 'Traditional Chalk Wash (Lime plaster)' },
      { id: 'r_d2', name: 'Scanned Work Station Hub', x: 67, y: 50, width: 5.6, height: 7.6, flooring: 'Raw Industrial Screed Concrete', wallFinish: 'Satin Off-White Acrylic Coating' }
    ];
    setRooms(simulatedRooms);
    setSelectedElementId('r_d1');
    setSelectedElementType('room');
    logTrace(`[CORE CALL] detectRooms() complete: Flood-fill identified ${simulatedRooms.length} enclosed zones.`);
  };

  const detectDoors = () => {
    const simulatedDoors: ArchDoor[] = [
      { id: 'd_d1', name: 'Main Threshold Swing', x: 26, y: 12, width: 1.0, angle: 90, style: 'swing', orientation: 'right' },
      { id: 'd_d2', name: 'Center Partition Sliding Door', x: 47, y: 48, width: 1.2, angle: 0, style: 'sliding', orientation: 'left' }
    ];
    setDoors(simulatedDoors);
    logTrace(`[CORE CALL] detectDoors() complete: Found ${simulatedDoors.length} standard doorway objects.`);
  };

  const detectWindows = () => {
    const simulatedWindows: ArchWindow[] = [
      { id: 'wi_d1', name: 'Scanned Facade Glass A', x: 67, y: 12, width: 2.0, glazing: 'triple', style: 'sliding' },
      { id: 'wi_d2', name: 'Scanned Facade Glass B', x: 88, y: 50, width: 1.5, glazing: 'double', style: 'casement' }
    ];
    setWindows(simulatedWindows);
    logTrace(`[CORE CALL] detectWindows() complete: Registered ${simulatedWindows.length} glazed structural window casings.`);
  };

  const setPlanScale = (scaleId: number) => {
    const scObj = SCALE_PRESETS.find(s => s.value === scaleId) || SCALE_PRESETS[0];
    setCurrentScale(scObj);
    logTrace(`[CORE CALL] setPlanScale(${scaleId}) - CAD coordinates locked at spatial constraint factors.`);
  };

  // Interactive add actions
  const handleAddWall = () => {
    const nWall: ArchWall = {
      id: `w_usr_${Date.now().toString().slice(-4)}`,
      name: `User Wall Segment ${walls.length + 1}`,
      startX: wallStartXPct,
      startY: wallStartYPct,
      endX: wallEndXPct,
      endY: wallEndYPct,
      thickness: wallTypeName === 'exterior' ? 300 : 150,
      type: wallTypeName
    };
    setWalls(prev => [...prev, nWall]);
    setSelectedElementId(nWall.id);
    setSelectedElementType('wall');
    logTrace(`[ARCH PANEL] Manually added Wall segment: "${nWall.name}" from (${wallStartXPct}%, ${wallStartYPct}%) to (${wallEndXPct}%, ${wallEndYPct}%).`);
  };

  const handleAddDoor = () => {
    const nDoor: ArchDoor = {
      id: `d_usr_${Date.now().toString().slice(-4)}`,
      name: `User Door Portal ${doors.length + 1}`,
      x: doorXPct,
      y: doorYPct,
      width: 0.9,
      angle: 90,
      style: doorStyleOption,
      orientation: 'right'
    };
    setDoors(prev => [...prev, nDoor]);
    setSelectedElementId(nDoor.id);
    setSelectedElementType('door');
    logTrace(`[ARCH PANEL] Positioned sliding/swing doorway: "${nDoor.name}" at location alignment point (${doorXPct}%, ${doorYPct}%).`);
  };

  const handleAddWindow = () => {
    const nWin: ArchWindow = {
      id: `wi_usr_${Date.now().toString().slice(-4)}`,
      name: `User Window Port ${windows.length + 1}`,
      x: winXPct,
      y: winYPct,
      width: 1.4,
      glazing: 'triple',
      style: winStyleOption
    };
    setWindows(prev => [...prev, nWin]);
    setSelectedElementId(nWin.id);
    setSelectedElementType('window');
    logTrace(`[ARCH PANEL] Fastened perimeter glazing component: "${nWin.name}" at coord (${winXPct}%, ${winYPct}%).`);
  };

  const handleAddRoom = () => {
    const nRoom: ArchRoom = {
      id: `r_usr_${Date.now().toString().slice(-4)}`,
      name: newRoomName || `Zone Lounge Floor ${rooms.length + 1}`,
      x: roomXPct,
      y: roomYPct,
      width: roomWidthM,
      height: roomHeightM,
      flooring: FLOORING_PRESETS[0],
      wallFinish: WALL_FINISH_PRESETS[0]
    };
    setRooms(prev => [...prev, nRoom]);
    setSelectedElementId(nRoom.id);
    setSelectedElementType('room');
    logTrace(`[ARCH PANEL] Provisioned architectural room space: "${nRoom.name}" of size ${roomWidthM}m x ${roomHeightM}m.`);
  };

  const handleDeleteElement = (id: string, type: 'wall' | 'room' | 'door' | 'window') => {
    if (type === 'wall') setWalls(prev => prev.filter(w => w.id !== id));
    if (type === 'room') setRooms(prev => prev.filter(r => r.id !== id));
    if (type === 'door') setDoors(prev => prev.filter(d => d.id !== id));
    if (type === 'window') setWindows(prev => prev.filter(wi => wi.id !== id));
    
    setSelectedElementId(null);
    setSelectedElementType(null);
    logTrace(`[ARCH KERNEL] Deleted element ID: ${id} (${type.toUpperCase()}). All schedules and dependencies updated.`);
  };

  // Compile elevation structure vectors
  const createElevation = (direction: 'North' | 'South' | 'East' | 'West') => {
    logTrace(`[CORE CALL] createElevation("${direction}"): Projecting elevation vectors from the "${direction}" horizon block...`);
    setActiveElevationDirection(direction);
  };

  const createSection = (sliceCoord: number) => {
    logTrace(`[CORE CALL] createSection(${sliceCoord}%): Extruding cross section slices under plane coordinate ${sliceCoord}%...`);
    setSectionPlaneX(sliceCoord);
  };

  // Export CAD Dossier Packages
  const exportArchitectureSheet = (format: 'pdf' | 'svg' | 'dxf' | 'project_file') => {
    logTrace(`[CORE CALL] exportArchitectureSheet("${format}"): Packaging architecture blueprint data...`);
    
    const projectPayload = {
      generatorId: "VisualOS_Architecture_Engine_v1.5",
      timestamp: new Date().toISOString(),
      activeProjectSchema: activePlanName,
      scalePreset: currentScale,
      physicalLayoutEntities: {
        wallsList: walls,
        roomsList: rooms,
        doorsList: doors,
        windowsList: windows
      },
      materialsNotes: rooms.map(r => ({
        room: r.name,
        floorSpec: r.flooring,
        wallWashSpec: r.wallFinish
      })),
      exportFormatSpec: format.toUpperCase()
    };

    const dataUri = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(projectPayload, null, 2));
    const downloadLink = document.createElement('a');
    downloadLink.setAttribute("href", dataUri);
    downloadLink.setAttribute("download", `${activePlanName.toLowerCase().replace(/\s+/g, '_')}_blueprint.${format}`);
    document.body.appendChild(downloadLink);
    downloadLink.click();
    downloadLink.remove();

    logTrace(`[ARCH EXPORT] Completed drafting bundle export to formats equivalent to standard DXF lines.`);
  };

  // Interactive click mappings inside blueprint
  const handleMapClickSelection = (id: string, type: 'wall' | 'room' | 'door' | 'window') => {
    setSelectedElementId(id);
    setSelectedElementType(type);
    logTrace(`[BLUEPRINT CANVAS] User selected element: "${id}" [${type.toUpperCase()}]`);
  };

  // Calculate dynamic surface boundaries for room schedules
  // Updates room schedule area dynamically whenever dimensions modify!
  const calculateRoomArea = (room: ArchRoom) => {
    // Basic scaling multiplier factor matching scales
    const multiplier = 50 / currentScale.value;
    const realW = room.width * multiplier;
    const realH = room.height * multiplier;
    return parseFloat((realW * realH).toFixed(1));
  };

  return (
    <div className="bg-slate-50 border border-gray-200 rounded-3xl p-5 shadow-sm space-y-6 animate-fadeIn text-xs text-slate-800">
      
      {/* Module Title */}
      <div className="flex items-center justify-between border-b border-gray-200 pb-3">
        <div>
          <span className="text-[10px] uppercase font-mono font-bold text-blue-600 block tracking-widest leading-none">BIM Drafting Core</span>
          <h3 className="text-sm font-extrabold text-slate-900 font-sans mt-0.5">Architecture Drawing Engine</h3>
        </div>
        <div className="flex items-center gap-2">
          <span className="px-1.5 py-0.5 bg-blue-100 border border-blue-200 text-blue-700 font-mono text-[9px] font-bold rounded uppercase">
            Active Scale Locked: {currentScale.value}
          </span>
        </div>
      </div>

      {/* Preset Floor Plans Row & Action Spawners */}
      <div className="space-y-1.5">
        <div className="flex justify-between items-center">
          <span className="text-[10px] font-mono font-bold text-gray-400 uppercase">Load Pre-Configured Scale Frameworks:</span>
          <span className="text-[9px] text-blue-600 font-semibold flex items-center gap-1">
            <Compass className="h-3 w-3" /> Scale Adjustments Recalculate Areas
          </span>
        </div>
        <div className="grid grid-cols-4 gap-1.5">
          {Object.keys(PRESET_FLOOR_PLANS).map((pKey) => (
            <button
              key={pKey}
              type="button"
              onClick={() => createFloorPlan(pKey)}
              className={`py-2 px-1 text-center font-bold rounded-lg border text-[9.5px] transition-all truncate leading-tight shadow-2xs ${
                activePlanName === PRESET_FLOOR_PLANS[pKey].name
                  ? 'bg-blue-600 text-white border-blue-600'
                  : 'bg-white hover:bg-slate-50 border-gray-250 text-slate-700'
              }`}
            >
              {PRESET_FLOOR_PLANS[pKey].name.split(" ")[0]}
            </button>
          ))}
        </div>
      </div>

      {/* File Upload / Scanner & Computer Vision Line Recognizers */}
      <div className="p-4 bg-white border border-gray-200 rounded-3xl space-y-3.5 shadow-2xs">
        <div className="flex items-center justify-between border-b pb-1.5">
          <span className="text-[10px] font-mono font-bold text-gray-500 uppercase flex items-center gap-1">
            <Upload className="h-3.5 w-3.5 text-blue-500" />
            1. Vector Scanner & CAD Pattern Synthesizer
          </span>
          <span className="text-[8.5px] font-mono text-gray-400">CORE ACTIONS</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <span className="block text-[9.5px] text-gray-500 leading-snug">
              Have existing floor plan images or blueprints? Drag them here to trigger pattern recognizers that synthesize raw lines into editable wall vectors and doors instantly.
            </span>
            <label className="relative flex flex-col items-center justify-center h-[72px] border-2 border-dashed border-gray-200 rounded-xl bg-slate-50/50 hover:bg-slate-50 cursor-pointer transition">
              <input 
                type="file" 
                accept="image/*,.pdf" 
                onChange={uploadFloorPlan}
                className="hidden" 
              />
              <div className="text-center space-y-1 p-2">
                <span className="text-[10px] font-sans font-bold text-blue-600 hover:underline">Click to Select CAD Blueprint</span>
                <span className="block text-[8px] text-gray-400">PDF, PNG, SVG or DWG formats accepted</span>
              </div>
            </label>
          </div>

          <div className="bg-slate-900 border border-slate-950 p-3 rounded-2xl flex flex-col justify-between min-h-[90px] font-mono text-[9px] text-emerald-400">
            <div className="flex items-center justify-between text-[8px] text-gray-400 font-bold uppercase tracking-wider">
              <span>BIM Extraction Pipeline LOGS</span>
              <span className="h-2 w-2 rounded-full bg-emerald-500 animate-ping" />
            </div>
            
            {uploadProgress !== null ? (
              <div className="space-y-2 my-2">
                <div className="flex justify-between items-center">
                  <span className="animate-pulse">{scannerLogStatus}</span>
                  <span>{uploadProgress}%</span>
                </div>
                <div className="w-full bg-white/10 h-1.5 rounded-full overflow-hidden">
                  <div className="bg-emerald-400 h-full transition-all duration-150" style={{ width: `${uploadProgress}%` }} />
                </div>
              </div>
            ) : (
              <div className="space-y-1 text-slate-300 py-1.5">
                <div>&gt; _ Ready to parser floor patterns.</div>
                <div>&gt; _ Walls, doors & windows are parsed as editable vectors.</div>
                <div>&gt; _ Room schedules dynamically link to spatial factors.</div>
              </div>
            )}

            <div className="grid grid-cols-4 gap-1 pt-1.5 border-t border-white/5 text-[8.5px] font-bold text-slate-400">
              <button type="button" onClick={detectWalls} className="hover:text-white transition">detectWalls()</button>
              <button type="button" onClick={detectRooms} className="hover:text-white transition">detectRooms()</button>
              <button type="button" onClick={detectDoors} className="hover:text-white transition">detectDoors()</button>
              <button type="button" onClick={detectWindows} className="hover:text-white transition">detectWindows()</button>
            </div>
          </div>
        </div>
      </div>

      {/* Presentation Tab View Selectors */}
      <div className="flex gap-1 bg-gray-200/50 p-1 rounded-2xl">
        {[
          { key: 'floor_plan', label: 'A. Interactive Floor Plan View', icon: Layout },
          { key: 'elevation', label: 'B. Projected Section Elevation', icon: Eye },
          { key: 'section', label: 'C. Internal Cross-Section Cut', icon: Ruler },
          { key: 'room_schedule', label: 'D. Schedule & Flooring Bill', icon: FileCheck }
        ].map((t) => {
          const Icon = t.icon;
          return (
            <button
              key={t.key}
              type="button"
              onClick={() => {
                setActivePresentationTab(t.key as any);
                logTrace(`[ARCH VIEW] Changed presentation sheet layer orientation to: "${t.label}"`);
              }}
              className={`flex-1 py-2 px-1 text-[10px] font-bold rounded-xl transition flex items-center justify-center gap-1.5 ${
                activePresentationTab === t.key
                  ? 'bg-slate-900 text-white shadow-sm'
                  : 'text-gray-600 hover:text-slate-905 hover:bg-white/50'
              }`}
            >
              <Icon className="h-3.5 w-3.5" />
              <span>{t.label.split(" .")[0].split(" ")[1]}</span>
            </button>
          );
        })}
      </div>

      {/* Main CAD Interactive Canvas Area */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        
        {/* SVG Drafting / Output Panel (Spans 2 columns on desktop) */}
        <div className="lg:col-span-2 bg-slate-950/95 border border-slate-900 rounded-3xl p-4 shadow-xl relative overflow-hidden min-h-[360px] flex flex-col justify-between text-slate-200">
          
          {/* Engineering Blueprint Radial Grids overlay */}
          <div className="absolute inset-0 bg-[radial-gradient(#ffffff04_1px,transparent_1px)] bg-[size:16px_16px] pointer-events-none" />
          <div className="absolute inset-0 border border-white/5 m-1 pointer-events-none" />
          
          {/* Blueprint Border Header Frame */}
          <div className="flex justify-between items-start border-b border-white/10 pb-2 relative z-10 font-mono text-[8.5px] text-cyan-400">
            <div>
              <div className="text-[7.5px] font-mono tracking-widest text-blue-400 uppercase bg-blue-500/10 px-1.5 py-0.5 rounded border border-blue-500/20 inline-block mb-1">
                SHEET: ARCH_LEVEL_01
              </div>
              <h4 className="text-xs font-bold text-white tracking-wide">{activePlanName}</h4>
            </div>
            <div className="text-right leading-none space-y-1">
              <div>PROJECT ID: #{Date.now().toString().slice(-6)}</div>
              <div>SCALE CONSTRAINT: {currentScale.label.split(" (")[0]}</div>
              <div>UNIT: METRIC (MM)</div>
            </div>
          </div>

          {/* Active Preset Visual Graphics */}
          <div className="flex-1 flex items-center justify-center relative my-6 min-h-[220px]">
            {activePresentationTab === 'floor_plan' && (
              <svg className="w-full h-[220px]" viewBox="0 0 100 100" preserveAspectRatio="none">
                
                {/* Visual grid ticks block */}
                <line x1="10" y1="5" x2="10" y2="95" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="30" y1="5" x2="30" y2="95" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="50" y1="5" x2="50" y2="95" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="70" y1="5" x2="70" y2="95" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="90" y1="5" x2="90" y2="95" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="5" y1="10" x2="95" y2="10" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="5" y1="30" x2="95" y2="30" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="5" y1="50" x2="95" y2="50" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="5" y1="70" x2="95" y2="70" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />
                <line x1="5" y1="90" x2="95" y2="90" stroke="rgba(255,255,255,0.02)" strokeWidth="0.5" strokeDasharray="1,2" />

                {/* Render Rooms Enclosure Shading */}
                {rooms.map((rm) => {
                  const isSelected = selectedElementId === rm.id && selectedElementType === 'room';
                  // Recalculate room coordinates representation based on width/height
                  const halfW = (rm.width * 2);
                  const halfH = (rm.height * 2);
                  const startX = Math.max(10, rm.x - halfW);
                  const startY = Math.max(10, rm.y - halfH);
                  const rectW = halfW * 2;
                  const rectH = halfH * 2;

                  return (
                    <g key={rm.id}>
                      <rect
                        x={startX}
                        y={startY}
                        width={rectW}
                        height={rectH}
                        rx="1"
                        fill={isSelected ? "rgba(6, 182, 212, 0.12)" : "rgba(37, 99, 235, 0.04)"}
                        stroke={isSelected ? "#06b6d4" : "rgba(255,255,255,0.05)"}
                        strokeWidth="0.5"
                        strokeDasharray={isSelected ? "1,1" : "none"}
                        onClick={() => handleMapClickSelection(rm.id, 'room')}
                        className="cursor-pointer hover:fill-blue-500/10 transition-colors"
                      />
                      {/* Room Label */}
                      <text
                        x={rm.x}
                        y={rm.y}
                        textAnchor="middle"
                        fill={isSelected ? "#22d3ee" : "#94a3b8"}
                        fontSize="2.5"
                        fontWeight="bold"
                        fontFamily="monospace"
                        className="pointer-events-none select-none"
                      >
                        {rm.name}
                      </text>
                      <text
                        x={rm.x}
                        y={rm.y + 3.2}
                        textAnchor="middle"
                        fill="#475569"
                        fontSize="2.0"
                        fontFamily="monospace"
                        className="pointer-events-none select-none"
                      >
                        {calculateRoomArea(rm)} m² ({rm.flooring.split(" (")[0]})
                      </text>
                    </g>
                  );
                })}

                {/* Render Walls */}
                {walls.map((wall) => {
                  const isSelected = selectedElementId === wall.id && selectedElementType === 'wall';
                  const thicknessRatio = wall.thickness / 1000; // mm to m ratio lines map
                  const wallWeight = wall.type === 'exterior' ? 2.5 : 1.25;

                  return (
                    <line
                      key={wall.id}
                      x1={wall.startX}
                      y1={wall.startY}
                      x2={wall.endX}
                      y2={wall.endY}
                      stroke={isSelected ? "#10b981" : wall.type === 'exterior' ? "#f8fafc" : "#64748b"}
                      strokeWidth={isSelected ? 3.0 : wallWeight}
                      strokeLinecap="square"
                      onClick={() => handleMapClickSelection(wall.id, 'wall')}
                      className="cursor-pointer hover:stroke-emerald-400 transition"
                    />
                  );
                })}

                {/* Render Doors */}
                {doors.map((door) => {
                  const isSelected = selectedElementId === door.id && selectedElementType === 'door';
                  // Doors visualized as simple arcs and open swing lines
                  const swingRadius = door.width * 4; // visual multiplier
                  
                  return (
                    <g key={door.id} className="cursor-pointer" onClick={() => handleMapClickSelection(door.id, 'door')}>
                      {/* Door hinge anchor point */}
                      <circle cx={door.x} cy={door.y} r="0.8" fill={isSelected ? "#06b6d4" : "#f43f5e"} />
                      
                      {/* Door leaf panel line */}
                      {door.style === 'swing' ? (
                        <>
                          {/* Closed door path line option */}
                          <line
                            x1={door.x}
                            y1={door.y}
                            x2={door.x + swingRadius}
                            y2={door.y - swingRadius}
                            stroke={isSelected ? "#06b6d4" : "#f43f5e"}
                            strokeWidth="0.8"
                          />
                          {/* Circle arc swing indication */}
                          <path
                            d={`M ${door.x + swingRadius} ${door.y} A ${swingRadius} ${swingRadius} 0 0 0 ${door.x} ${door.y - swingRadius}`}
                            fill="none"
                            stroke={isSelected ? "rgba(6, 182, 212, 0.4)" : "rgba(244, 63, 94, 0.25)"}
                            strokeWidth="0.5"
                            strokeDasharray="1,1"
                          />
                        </>
                      ) : (
                        /* Sliding door path */
                        <rect
                          x={door.x - swingRadius}
                          y={door.y - 1}
                          width={swingRadius * 2}
                          height="2"
                          fill="rgba(244, 63, 94, 0.15)"
                          stroke={isSelected ? "#06b6d4" : "#f43f5e"}
                          strokeWidth="0.6"
                        />
                      )}
                      
                      {/* Small text label */}
                      <text
                        x={door.x}
                        y={door.y + 3.5}
                        textAnchor="middle"
                        fill="#f43f5e"
                        fontSize="1.8"
                        fontFamily="monospace"
                      >
                        {door.width}m Door
                      </text>
                    </g>
                  );
                })}

                {/* Render Windows */}
                {windows.map((win) => {
                  const isSelected = selectedElementId === win.id && selectedElementType === 'window';
                  const widthSpan = win.width * 4; // visual multiplier

                  return (
                    <g key={win.id} className="cursor-pointer" onClick={() => handleMapClickSelection(win.id, 'window')}>
                      {/* Drawn as double thin parallel cyan frames inside walls */}
                      <rect
                        x={win.x - widthSpan / 2}
                        y={win.y - 0.75}
                        width={widthSpan}
                        height="1.5"
                        fill="#10b981"
                        stroke={isSelected ? "#06b6d4" : "#a855f7"}
                        strokeWidth="0.6"
                      />
                      <line
                        x1={win.x - widthSpan / 2}
                        y1={win.y}
                        x2={win.x + widthSpan / 2}
                        y2={win.y}
                        stroke="#fff"
                        strokeWidth="0.4"
                      />
                      {/* Window text label */}
                      <text
                        x={win.x}
                        y={win.y - 2.5}
                        textAnchor="middle"
                        fill="#a855f7"
                        fontSize="1.8"
                        fontFamily="monospace"
                      >
                        {win.width}m Window
                      </text>
                    </g>
                  );
                })}

                {/* Architectural Arrow Dimension Ticks Guidelines */}
                <g stroke="#3b82f6" strokeWidth="0.30">
                  <line x1="10" y1="94" x2="90" y2="94" />
                  <line x1="10" y1="92" x2="10" y2="96" />
                  <line x1="90" y1="92" x2="90" y2="96" strokeWidth="0.4" />
                </g>
                <text x="50" y="97.5" textAnchor="middle" fill="#3b82f6" fontSize="2.2" fontFamily="monospace">
                  TOTAL ENVELOPE BOUNDARY WIDTH: 16.0 meters (Scale 1:{currentScale.value})
                </text>
              </svg>
            )}

            {activePresentationTab === 'elevation' && (
              <div className="w-full h-full flex flex-col justify-between">
                {/* Elevation Controls Bar */}
                <div className="flex items-center justify-between bg-black/40 border border-white/15 px-3 py-1.5 rounded-xl text-[9px] font-mono mb-2">
                  <span className="text-cyan-400">ACTIVE PROJECTION ORIENTATION:</span>
                  <div className="flex gap-1.5">
                    {(['North', 'South', 'East', 'West'] as const).map(dir => (
                      <button
                        key={dir}
                        type="button"
                        onClick={() => createElevation(dir)}
                        className={`px-2 py-0.5 rounded ${
                          activeElevationDirection === dir ? 'bg-cyan-600 text-white font-bold' : 'bg-white/5 hover:bg-white/10'
                        }`}
                      >
                        {dir} Elevation
                      </button>
                    ))}
                  </div>
                </div>

                {/* Render Projected SVG Elevation */}
                <svg className="w-full h-[180px]" viewBox="0 0 200 100">
                  {/* Sky/Atmosphere Grid gradient */}
                  <rect x="10" y="10" width="180" height="80" fill="rgba(8, 47, 73, 0.3)" rx="4" />
                  
                  {/* Ground Line */}
                  <line x1="10" y1="80" x2="190" y2="80" stroke="#06b6d4" strokeWidth="2" />
                  
                  {/* Outer structural mass box outline based on rooms depth */}
                  <rect x="30" y="30" width="140" height="50" fill="none" stroke="#e2e8f0" strokeWidth="2" />
                  {/* Shading concrete/ashlar texture stripes */}
                  <line x1="30" y1="40" x2="170" y2="40" stroke="rgba(255,255,255,0.05)" strokeWidth="0.5" />
                  <line x1="30" y1="50" x2="170" y2="50" stroke="rgba(255,255,255,0.05)" strokeWidth="0.5" />
                  <line x1="30" y1="60" x2="170" y2="60" stroke="rgba(255,255,255,0.05)" strokeWidth="0.5" />
                  <line x1="30" y1="70" x2="170" y2="70" stroke="rgba(255,255,255,0.05)" strokeWidth="0.5" />

                  {/* Sloped Roof rafter outline */}
                  <polygon points="25,30 100,10 175,30" fill="none" stroke="#f43f5e" strokeWidth="1.5" />
                  <text x="100" y="8" textAnchor="middle" fill="#f43f5e" fontSize="5" fontFamily="monospace">ROOF LEVEL HEIGHT: 5.50m</text>

                  {/* Windows elevations matching layouts */}
                  <rect x="45" y="45" width="25" height="15" fill="rgba(6, 182, 212, 0.15)" stroke="#38bdf8" strokeWidth="1.2" />
                  <line x1="57.5" y1="45" x2="57.5" y2="60" stroke="#38bdf8" strokeWidth="0.8" />
                  <text x="57.5" y="63" textAnchor="middle" fill="#94a3b8" fontSize="4">Glazed Win</text>

                  {/* Entrance Door elevation */}
                  <rect x="110" y="45" width="20" height="35" fill="rgba(244, 63, 94, 0.15)" stroke="#f43f5e" strokeWidth="1.5" />
                  <circle cx="114" cy="62" r="1.5" fill="#e2e8f0" />
                  <text x="120" y="42" textAnchor="middle" fill="#f43f5e" fontSize="4">Active Pivot Door</text>

                  <text x="100" y="92" textAnchor="middle" fill="#94a3b8" fontSize="5" fontFamily="monospace">
                    PROJECTION LOOKING DIRECTLY {activeElevationDirection.toUpperCase()} AT MAIN PERIMETER MASONRY
                  </text>
                </svg>
              </div>
            )}

            {activePresentationTab === 'section' && (
              <div className="w-full h-full flex flex-col justify-between">
                {/* Section Controls Bar */}
                <div className="flex items-center justify-between bg-black/40 border border-white/15 px-3 py-1.5 rounded-xl text-[9px] font-mono mb-2">
                  <span className="text-cyan-400">SECTION PLANE CUT LINE X-COORDS:</span>
                  <div className="flex items-center gap-2">
                    <input
                      type="range"
                      min="10"
                      max="90"
                      value={sectionPlaneX}
                      onChange={(e) => createSection(parseInt(e.target.value))}
                      className="w-24 accent-cyan-500 bg-white/20"
                    />
                    <span className="text-white font-bold">{sectionPlaneX}% Width Plane</span>
                  </div>
                </div>

                {/* Render Cross Section Cut SVG */}
                <svg className="w-full h-[180px]" viewBox="0 0 200 100">
                  {/* Sliced structure walls showing solid hatch marks */}
                  {/* Left wall slice */}
                  <rect x="25" y="25" width="10" height="55" fill="rgba(244, 63, 94, 0.4)" stroke="#ef4444" strokeWidth="1" />
                  <line x1="25" y1="30" x2="35" y2="40" stroke="#ef4444" strokeWidth="0.5" />
                  <line x1="25" y1="45" x2="35" y2="55" stroke="#ef4444" strokeWidth="0.5" />
                  <line x1="25" y1="60" x2="35" y2="70" stroke="#ef4444" strokeWidth="0.5" />

                  {/* Mid divider internal wall slice */}
                  <rect x="105" y="25" width="6" height="55" fill="rgba(99, 102, 241, 0.4)" stroke="#6366f1" strokeWidth="1" />
                  <line x1="105" y1="35" x2="111" y2="41" stroke="#6366f1" strokeWidth="0.5" />
                  <line x1="105" y1="55" x2="111" y2="61" stroke="#6366f1" strokeWidth="0.5" />

                  {/* Right boundary wall slice */}
                  <rect x="165" y="25" width="10" height="55" fill="rgba(244, 63, 94, 0.4)" stroke="#ef4444" strokeWidth="1" />
                  <line x1="165" y1="30" x2="175" y2="40" stroke="#ef4444" strokeWidth="0.5" />
                  <line x1="165" y1="50" x2="175" y2="60" stroke="#ef4444" strokeWidth="0.5" />

                  {/* Floor slab slice concrete block */}
                  <rect x="15" y="80" width="170" height="12" fill="rgba(148, 163, 184, 0.3)" stroke="#fff" strokeWidth="1" />
                  <text x="100" y="88" textAnchor="middle" fill="#ffffff" fontSize="4.5" fontFamily="monospace">REINFORCED CONCRETE PLATFORM FOOTHOLD (150mm)</text>

                  {/* Ceiling Joist plate section */}
                  <rect x="25" y="22" width="150" height="3" fill="#64748b" />
                  <text x="100" y="18" textAnchor="middle" fill="#64748b" fontSize="4.5">CEILING GAPS JOIST SPACE: 2.80m Height</text>

                  {/* Hanging Light fixture interior indicator */}
                  <line x1="68" y1="25" x2="68" y2="45" stroke="#f59e0b" strokeWidth="1" />
                  <circle cx="68" cy="48" r="3" fill="#fbbf24" />

                  <text x="100" y="97" textAnchor="middle" fill="#94a3b8" fontSize="4.5" fontFamily="monospace">
                    BIM MODEL SLICE REPRESENTING INTERNAL TIMBER BEAMS AND FLOOR PLATES
                  </text>
                </svg>
              </div>
            )}

            {activePresentationTab === 'room_schedule' && (
              <div className="w-full h-full bg-slate-900 border border-white/10 rounded-2xl p-4 overflow-y-auto max-h-[220px]">
                <div className="flex justify-between items-center border-b border-white/10 pb-1.5 mb-2 text-[10px] font-mono text-cyan-400">
                  <span className="font-bold">LIVE SYNCHRONIZED BIM ROOM SCHEDULE</span>
                  <span>{rooms.length} ENCLOSURES</span>
                </div>
                
                <table className="w-full text-left font-mono text-[9.5px]">
                  <thead>
                    <tr className="border-b border-white/5 text-gray-400">
                      <th className="py-1">Room ID</th>
                      <th className="py-1">Enclosure Name</th>
                      <th className="py-1">Computed Area</th>
                      <th className="py-1">Flooring Spec</th>
                      <th className="py-1">Wall Finish</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {rooms.map((rm) => (
                      <tr 
                        key={rm.id} 
                        onClick={() => handleMapClickSelection(rm.id, 'room')}
                        className={`hover:bg-white/5 cursor-pointer transition ${
                          selectedElementId === rm.id ? 'bg-cyan-950/40 text-cyan-300 font-bold' : ''
                        }`}
                      >
                        <td className="py-1.5">{rm.id}</td>
                        <td className="py-1.5 text-white">{rm.name}</td>
                        <td className="py-1.5">{calculateRoomArea(rm)} m²</td>
                        <td className="py-1.5 text-blue-300">{rm.flooring.split(" (")[0]}</td>
                        <td className="py-1.5 text-purple-300">{rm.wallFinish.split(" (")[0]}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Quick HUD Selected Element Inspector readout */}
          {selectedElementId ? (
            <div className="bg-slate-900/80 border border-white/10 p-3 rounded-2xl backdrop-blur-xs relative z-10 flex items-center justify-between gap-4 animate-fadeIn">
              <div className="flex items-center gap-3">
                <span className="p-2 bg-blue-500/10 border border-blue-500/20 rounded-xl text-blue-400">
                  {selectedElementType === 'room' && <Home className="h-4 w-4" />}
                  {selectedElementType === 'wall' && <Layers className="h-4 w-4" />}
                  {selectedElementType === 'door' && <Layout className="h-4 w-4" />}
                  {selectedElementType === 'window' && <Grid className="h-4 w-4" />}
                </span>
                <div>
                  <div className="flex items-center gap-1.5">
                    <span className="text-[10.5px] font-bold text-white font-sans">
                      {selectedElementType === 'room' && rooms.find(r => r.id === selectedElementId)?.name}
                      {selectedElementType === 'wall' && walls.find(w => w.id === selectedElementId)?.name}
                      {selectedElementType === 'door' && doors.find(d => d.id === selectedElementId)?.name}
                      {selectedElementType === 'window' && windows.find(wi => wi.id === selectedElementId)?.name}
                    </span>
                    <span className="text-[8px] font-mono text-gray-500">ID: {selectedElementId}</span>
                  </div>
                  <p className="text-[9.5px] text-gray-400 leading-none mt-1">
                    {selectedElementType === 'room' && `Calculated Area: ${calculateRoomArea(rooms.find(r => r.id === selectedElementId)!)} m² | Flooring: ${rooms.find(r => r.id === selectedElementId)?.flooring}`}
                    {selectedElementType === 'wall' && `Thickness: ${walls.find(w => w.id === selectedElementId)?.thickness}mm | Type: ${walls.find(w => w.id === selectedElementId)?.type.toUpperCase()}`}
                    {selectedElementType === 'door' && `Style: ${doors.find(d => d.id === selectedElementId)?.style.toUpperCase()} | Width: ${doors.find(d => d.id === selectedElementId)?.width}m`}
                    {selectedElementType === 'window' && `Glazing: ${windows.find(wi => wi.id === selectedElementId)?.glazing.toUpperCase()} | Model: ${windows.find(wi => wi.id === selectedElementId)?.style}`}
                  </p>
                </div>
              </div>

              <button
                type="button"
                onClick={() => handleDeleteElement(selectedElementId, selectedElementType!)}
                className="py-1 px-2.5 bg-red-600/20 hover:bg-red-650/30 border border-red-500/30 text-red-300 text-[9px] font-bold uppercase rounded-lg transition"
              >
                Delete
              </button>
            </div>
          ) : (
            <div className="bg-slate-900/35 border border-white/5 p-3 rounded-2xl text-[9.5px] text-gray-500 text-center font-mono py-4">
              &gt; _ Select any wall segment, door pivot, or room casing above to inspect standard editable properties.
            </div>
          )}

        </div>

        {/* CAD Properties Inspector Sidebar */}
        <div className="space-y-4">
          
          {/* Section: Plan Elements Configurator */}
          <div className="bg-white border border-gray-200 rounded-3xl p-4 space-y-4 shadow-2xs">
            <div className="flex justify-between items-center border-b pb-1.5">
              <span className="text-[10px] font-mono font-bold text-gray-500 uppercase flex items-center gap-1">
                <Sliders className="h-3.5 w-3.5 text-indigo-500" />
                2. CAD Inspector & Property Modifier
              </span>
              <span className="px-1.5 py-0.5 bg-indigo-50 text-indigo-700 text-[8.5px] font-mono font-bold rounded">EDITABLE</span>
            </div>

            {/* Editable Inspector inputs when Room is active */}
            {selectedElementType === 'room' && selectedElementId && (() => {
              const activeRoom = rooms.find(r => r.id === selectedElementId);
              if (!activeRoom) return null;
              return (
                <div className="space-y-3">
                  <div className="p-2 bg-indigo-50/50 border border-indigo-100 rounded-xl space-y-1">
                    <span className="text-[9px] font-mono font-bold text-indigo-600 block">SELECTED ROOM SPECIFICATIONS:</span>
                    <span className="text-xs font-bold font-sans text-slate-800">{activeRoom.name}</span>
                  </div>

                  {/* Room name modifier */}
                  <div className="space-y-1">
                    <label className="text-[9px] font-mono text-gray-400 uppercase">Modify Room Name:</label>
                    <input
                      type="text"
                      value={activeRoom.name}
                      onChange={(e) => {
                        const nextName = e.target.value;
                        setRooms(prev => prev.map(r => r.id === selectedElementId ? { ...r, name: nextName } : r));
                      }}
                      className="w-full p-1.5 bg-gray-50 border border-gray-200 rounded-lg text-xs"
                    />
                  </div>

                  {/* Width & Height modifier */}
                  <div className="grid grid-cols-2 gap-2">
                    <div className="space-y-1">
                      <label className="text-[9px] font-mono text-gray-400 uppercase">Width (meters):</label>
                      <input
                        type="number"
                        step="0.2"
                        value={activeRoom.width}
                        onChange={(e) => {
                          const val = parseFloat(e.target.value) || 1.0;
                          setRooms(prev => prev.map(r => r.id === selectedElementId ? { ...r, width: val } : r));
                        }}
                        className="w-full p-1.2 bg-gray-50 border border-gray-200 rounded-lg text-xs"
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[9px] font-mono text-gray-400 uppercase">Height (meters):</label>
                      <input
                        type="number"
                        step="0.2"
                        value={activeRoom.height}
                        onChange={(e) => {
                          const val = parseFloat(e.target.value) || 1.0;
                          setRooms(prev => prev.map(r => r.id === selectedElementId ? { ...r, height: val } : r));
                        }}
                        className="w-full p-1.2 bg-gray-50 border border-gray-200 rounded-lg text-xs"
                      />
                    </div>
                  </div>

                  {/* Flooring material drop menu */}
                  <div className="space-y-1">
                    <label className="text-[9px] font-mono text-gray-400 uppercase">Lock Flooring Material Spec:</label>
                    <select
                      value={activeRoom.flooring}
                      onChange={(e) => {
                        const val = e.target.value;
                        setRooms(prev => prev.map(r => r.id === selectedElementId ? { ...r, flooring: val } : r));
                        logTrace(`[SPEC UPDATE] Floor specification on "${activeRoom.name}" matched: ${val}`);
                      }}
                      className="w-full p-1.5 bg-white border border-gray-200 rounded-lg text-xs"
                    >
                      {FLOORING_PRESETS.map((fl) => (
                        <option key={fl} value={fl}>{fl}</option>
                      ))}
                    </select>
                  </div>

                  {/* Wall finish drop menu */}
                  <div className="space-y-1">
                    <label className="text-[9px] font-mono text-gray-400 uppercase">Lock Wall Coating Finishes:</label>
                    <select
                      value={activeRoom.wallFinish}
                      onChange={(e) => {
                        const val = e.target.value;
                        setRooms(prev => prev.map(r => r.id === selectedElementId ? { ...r, wallFinish: val } : r));
                        logTrace(`[SPEC UPDATE] Wall finish parameter saved: "${val}"`);
                      }}
                      className="w-full p-1.5 bg-white border border-gray-200 rounded-lg text-xs"
                    >
                      {WALL_FINISH_PRESETS.map((wf) => (
                        <option key={wf} value={wf}>{wf}</option>
                      ))}
                    </select>
                  </div>
                </div>
              );
            })()}

            {/* Editable Inspector inputs when Wall is active */}
            {selectedElementType === 'wall' && selectedElementId && (() => {
              const activeWall = walls.find(w => w.id === selectedElementId);
              if (!activeWall) return null;
              return (
                <div className="space-y-3">
                  <div className="p-2 bg-emerald-50 border border-emerald-100 rounded-xl space-y-1">
                    <span className="text-[9px] font-mono font-bold text-emerald-600 block">SELECTED WALL PATH:</span>
                    <span className="text-xs font-bold font-sans text-slate-800">{activeWall.name}</span>
                  </div>

                  <div className="space-y-1">
                    <label className="text-[9px] font-mono text-gray-400 uppercase">Wall Segment Title:</label>
                    <input
                      type="text"
                      value={activeWall.name}
                      onChange={(e) => {
                        const val = e.target.value;
                        setWalls(prev => prev.map(w => w.id === selectedElementId ? { ...w, name: val } : w));
                      }}
                      className="w-full p-1.5 bg-gray-50 border border-gray-200 rounded-lg text-xs"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-2">
                    <div className="space-y-1">
                      <label className="text-[9px] font-mono text-gray-400 uppercase">Core Thickness (mm):</label>
                      <input
                        type="number"
                        step="50"
                        value={activeWall.thickness}
                        onChange={(e) => {
                          const val = parseInt(e.target.value) || 100;
                          setWalls(prev => prev.map(w => w.id === selectedElementId ? { ...w, thickness: val } : w));
                        }}
                        className="w-full p-1 bg-gray-50 border border-gray-200 rounded-lg text-xs"
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[9px] font-mono text-gray-400 uppercase">Structural Class:</label>
                      <select
                        value={activeWall.type}
                        onChange={(e) => {
                          const val = e.target.value as 'exterior' | 'interior';
                          setWalls(prev => prev.map(w => w.id === selectedElementId ? { ...w, type: val } : w));
                        }}
                        className="w-full p-1 bg-white border border-gray-200 rounded-lg text-xs"
                      >
                        <option value="exterior">Exterior (Load-Bearing)</option>
                        <option value="interior">Interior (Partition)</option>
                      </select>
                    </div>
                  </div>
                </div>
              );
            })()}

            {/* Editable Inspector inputs when Door / Window is active */}
            {(selectedElementType === 'door' || selectedElementType === 'window') && selectedElementId && (() => {
              const activeDoor = doors.find(d => d.id === selectedElementId);
              const activeWin = windows.find(wi => wi.id === selectedElementId);
              return (
                <div className="space-y-3">
                  <div className="p-2 bg-pink-50 border border-pink-100 rounded-xl space-y-1">
                    <span className="text-[9px] font-mono font-bold text-pink-600 block">SELECTED APERTURE OBJECT:</span>
                    <span className="text-xs font-bold font-sans text-slate-800">
                      {selectedElementType === 'door' ? activeDoor?.name : activeWin?.name}
                    </span>
                  </div>

                  <div className="space-y-1">
                    <label className="text-[9px] font-mono text-gray-400 uppercase">Object Aperture Tag:</label>
                    <input
                      type="text"
                      value={selectedElementType === 'door' ? activeDoor?.name : activeWin?.name}
                      onChange={(e) => {
                        const val = e.target.value;
                        if (selectedElementType === 'door') {
                          setDoors(prev => prev.map(d => d.id === selectedElementId ? { ...d, name: val } : d));
                        } else {
                          setWindows(prev => prev.map(wi => wi.id === selectedElementId ? { ...wi, name: val } : wi));
                        }
                      }}
                      className="w-full p-1.5 bg-gray-50 border border-gray-200 rounded-lg text-xs"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-2">
                    <div className="space-y-1">
                      <label className="text-[9px] font-mono text-gray-400 uppercase">Passage Width (m):</label>
                      <input
                        type="number"
                        step="0.1"
                        value={selectedElementType === 'door' ? activeDoor?.width : activeWin?.width}
                        onChange={(e) => {
                          const val = parseFloat(e.target.value) || 0.5;
                          if (selectedElementType === 'door') {
                            setDoors(prev => prev.map(d => d.id === selectedElementId ? { ...d, width: val } : d));
                          } else {
                            setWindows(prev => prev.map(wi => wi.id === selectedElementId ? { ...wi, width: val } : wi));
                          }
                        }}
                        className="w-full p-1 bg-gray-50 border border-gray-200 rounded-lg text-xs"
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[9px] font-mono text-gray-400 uppercase">Style Assembly:</label>
                      {selectedElementType === 'door' ? (
                        <select
                          value={activeDoor?.style}
                          onChange={(e) => {
                            const val = e.target.value as any;
                            setDoors(prev => prev.map(d => d.id === selectedElementId ? { ...d, style: val } : d));
                          }}
                          className="w-full p-1 bg-white border border-gray-200 rounded-lg text-xs"
                        >
                          <option value="swing">90° Swing Panel</option>
                          <option value="sliding">Flush Wall Pocket Sliding</option>
                          <option value="bifold">Hinged Bi-Fold Accordion</option>
                        </select>
                      ) : (
                        <select
                          value={activeWin?.style}
                          onChange={(e) => {
                            const val = e.target.value as any;
                            setWindows(prev => prev.map(wi => wi.id === selectedElementId ? { ...wi, style: val } : wi));
                          }}
                          className="w-full p-1 bg-white border border-gray-200 rounded-lg text-xs"
                        >
                          <option value="sliding">Horizontal Track Slider</option>
                          <option value="casement">External Outward Casement</option>
                          <option value="fixed">Fixed Structural Pane</option>
                        </select>
                      )}
                    </div>
                  </div>
                </div>
              );
            })()}

            {/* Default prompt when nothing selected */}
            {!selectedElementId && (
              <div className="p-3 bg-gray-50 rounded-xl text-center text-gray-400 text-[10px] py-6 leading-relaxed">
                Click any room box, wall coordinate line, door swing, or window tile on the canvas workspace on the left to activate full properties customization panels.
              </div>
            )}
          </div>

          {/* Section: Component Generator Plotters */}
          <div className="bg-white border border-gray-200 rounded-3xl p-4 space-y-4 shadow-2xs">
            <div className="flex justify-between items-center border-b pb-1.5">
              <span className="text-[10px] font-mono font-bold text-gray-500 uppercase flex items-center gap-1">
                <Plus className="h-3.5 w-3.5 text-blue-500" />
                3. CAD Element Assembly Spawner
              </span>
              <span className="text-[8px] font-mono text-gray-400">APPEND OBJECTS</span>
            </div>

            <div className="space-y-4">
              
              {/* Spawner A: Add Custom Room Box */}
              <div className="space-y-2 p-3 bg-slate-50 border border-slate-100 rounded-2xl">
                <span className="block text-[9px] font-mono text-slate-500 uppercase leading-none font-bold">A. Spawn Enclosed Room Casing</span>
                <div className="grid grid-cols-2 gap-1.5">
                  <input
                    type="text"
                    placeholder="Room Name"
                    value={newRoomName}
                    onChange={(e) => setNewRoomName(e.target.value)}
                    className="p-1 px-1.5 bg-white border rounded-lg text-xs"
                  />
                  <div className="flex gap-1">
                    <input
                      type="number"
                      step="0.5"
                      placeholder="W"
                      value={roomWidthM}
                      onChange={(e) => setRoomWidthM(parseFloat(e.target.value) || 3.0)}
                      className="p-1 w-full bg-white border rounded-lg text-xs text-center"
                      title="Width (m)"
                    />
                    <input
                      type="number"
                      step="0.5"
                      placeholder="H"
                      value={roomHeightM}
                      onChange={(e) => setRoomHeightM(parseFloat(e.target.value) || 3.0)}
                      className="p-1 w-full bg-white border rounded-lg text-xs text-center"
                      title="Height (m)"
                    />
                  </div>
                  <div className="flex gap-1 col-span-2">
                    <input
                      type="number"
                      placeholder="X Pct"
                      value={roomXPct}
                      onChange={(e) => setRoomXPct(parseInt(e.target.value) || 50)}
                      className="p-1 w-full bg-white border rounded-lg text-xs text-center"
                      title="X grid percent (10-90)"
                    />
                    <input
                      type="number"
                      placeholder="Y Pct"
                      value={roomYPct}
                      onChange={(e) => setRoomYPct(parseInt(e.target.value) || 50)}
                      className="p-1 w-full bg-white border rounded-lg text-xs text-center"
                      title="Y grid percent (10-90)"
                    />
                  </div>
                </div>
                <button
                  type="button"
                  onClick={handleAddRoom}
                  className="w-full py-1.5 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl text-[9.5px] uppercase tracking-wider block text-center shadow-2xs transition"
                >
                  Spawn Room Entity
                </button>
              </div>

              {/* Spawner B: Add Wall Coordinate Path */}
              <div className="space-y-2 p-3 bg-slate-50 border border-slate-100 rounded-2xl">
                <span className="block text-[9px] font-mono text-slate-500 uppercase leading-none font-bold">B. Append Wall Path Segment</span>
                <div className="grid grid-cols-2 gap-1.5 text-center">
                  <div className="space-y-0.5">
                    <span className="text-[8px] font-mono text-gray-400">Start (X%, Y%)</span>
                    <div className="flex gap-1 justify-center">
                      <input type="number" value={wallStartXPct} onChange={(e) => setWallStartXPct(parseInt(e.target.value) || 10)} className="w-10 bg-white border text-center text-xs rounded" />
                      <input type="number" value={wallStartYPct} onChange={(e) => setWallStartYPct(parseInt(e.target.value) || 10)} className="w-10 bg-white border text-center text-xs rounded" />
                    </div>
                  </div>
                  <div className="space-y-0.5">
                    <span className="text-[8px] font-mono text-gray-400">End (X%, Y%)</span>
                    <div className="flex gap-1 justify-center">
                      <input type="number" value={wallEndXPct} onChange={(e) => setWallEndXPct(parseInt(e.target.value) || 90)} className="w-10 bg-white border text-center text-xs rounded" />
                      <input type="number" value={wallEndYPct} onChange={(e) => setWallEndYPct(parseInt(e.target.value) || 90)} className="w-10 bg-white border text-center text-xs rounded" />
                    </div>
                  </div>
                  <select
                    value={wallTypeName}
                    onChange={(e) => setWallTypeName(e.target.value as any)}
                    className="p-1 bg-white border rounded-lg text-xs col-span-2"
                  >
                    <option value="exterior">Exterior (Load weight, 300mm)</option>
                    <option value="interior">Interior (Partition separator, 150mm)</option>
                  </select>
                </div>
                <button
                  type="button"
                  onClick={handleAddWall}
                  className="w-full py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl text-[9.5px] uppercase tracking-wider block text-center shadow-2xs transition"
                >
                  Draw Wall Path
                </button>
              </div>

              {/* Spawner C: Add Door aperture */}
              <div className="space-y-2 p-3 bg-slate-50 border border-slate-100 rounded-2xl">
                <span className="block text-[9px] font-mono text-slate-500 uppercase leading-none font-bold">C. Place Door/Window Aperture</span>
                <div className="grid grid-cols-2 gap-1.5">
                  <div className="space-y-0.5">
                    <span className="text-[8px] font-mono text-gray-400">X Grid %</span>
                    <input type="number" value={doorXPct} onChange={(e) => { setDoorXPct(parseInt(e.target.value) || 50); setWinXPct(parseInt(e.target.value) || 75); }} className="w-full bg-white border p-0.5 text-center text-xs rounded" />
                  </div>
                  <div className="space-y-0.5">
                    <span className="text-[8px] font-mono text-gray-400">Y Grid %</span>
                    <input type="number" value={doorYPct} onChange={(e) => { setDoorYPct(parseInt(e.target.value) || 10); setWinYPct(parseInt(e.target.value) || 10); }} className="w-full bg-white border p-0.5 text-center text-xs rounded" />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-1">
                  <button
                    type="button"
                    onClick={handleAddDoor}
                    className="py-1 px-1 bg-pink-100 hover:bg-pink-200 border border-pink-300 text-pink-800 text-[8.5px] font-bold rounded-lg uppercase transition"
                  >
                    + Place Door
                  </button>
                  <button
                    type="button"
                    onClick={handleAddWindow}
                    className="py-1 px-1 bg-purple-100 hover:bg-purple-200 border border-purple-300 text-purple-800 text-[8.5px] font-bold rounded-lg uppercase transition"
                  >
                    + Place Windows
                  </button>
                </div>
              </div>

            </div>
          </div>

          {/* Section: Scale adjustments */}
          <div className="bg-white border border-gray-200 rounded-3xl p-4 space-y-3 shadow-2xs">
            <span className="block text-[10px] font-mono font-bold text-gray-500 uppercase border-b pb-1">
              Active Scaling Lock Configurations
            </span>
            <div className="space-y-2">
              {SCALE_PRESETS.map((sc) => (
                <button
                  key={sc.value}
                  type="button"
                  onClick={() => setPlanScale(sc.value)}
                  className={`w-full py-1.5 px-3 text-left rounded-xl border text-[9px] transition-all font-mono leading-tight shadow-3xs flex items-center justify-between ${
                    currentScale.value === sc.value
                      ? 'bg-blue-50 border-blue-400 text-blue-750 font-bold ring-1 ring-blue-400/40'
                      : 'bg-white hover:bg-slate-50 border-gray-200 text-gray-600'
                  }`}
                >
                  <span>{sc.label.split(" (")[0]}</span>
                  <span className="text-[8px] opacity-60">Factor: {sc.factor}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Section: Dossier Compiler Exporter Tool */}
          <div className="p-4 bg-white border border-gray-200 rounded-3xl space-y-3.5 shadow-2xs">
            <span className="block text-[10px] font-mono font-bold text-gray-500 uppercase border-b pb-1">
              Dossier Blueprint Exporter Tool
            </span>
            <div className="grid grid-cols-2 gap-1.5">
              {(['svg', 'pdf', 'dxf', 'project_file'] as const).map(fmt => (
                <button
                  key={`exp-arch-${fmt}`}
                  type="button"
                  onClick={() => exportArchitectureSheet(fmt)}
                  className="py-2 bg-white hover:bg-blue-50 border border-gray-200 rounded-xl text-center text-[9.5px] font-bold uppercase text-slate-705 shadow-2xs flex items-center justify-center gap-1 transition"
                >
                  <Download className="h-3 w-3 text-gray-400" />
                  <span>{fmt === 'project_file' ? 'BIM JSON' : `${fmt.toUpperCase()} Sheet`}</span>
                </button>
              ))}
            </div>
          </div>

        </div>

      </div>

    </div>
  );
}
